### PR TITLE
Accessibility fixes

### LINKED ISSUE #77: Accessibility Issues:  Missing form label, Empty form label
Update Springshare search form in ukltophdr_sitehdr HTML chunk.

### LINKED ISSUE #78: Accessibility Issue:  Empty button
Add accessibility attributes to mobile 'more' menu button.

### PR DESCRIPTION
**Pull request by libmanuk**
closes #77
closes #78

### CODE REVIEW

File: js/universalHeader.js [hunk 1]
```diff
@@ -47,7 +47,7 @@ const header_strings = {
...
...v class="ukl-ext-clamp"><header id="ukl-main-header" class="ukl-global-header "><div class="ukl-slab"><div class="ukl-slab__wrapper"><div class="ukl-global-header"><div class="ukl-global-header-layout"><div id="ukl-gethome"></div><span id="ukl-gethdrw"></span> <div class="ukl-nav-links"><div class="ukl-link" id="ukl-link1"><div class="ukl-getlink" id="ukl-getlink1"></div></div><div class="ukl-link" id="ukl-link2"><div class="ukl-getlink" id="ukl-getlink2"></div></div><div class="ukl-link" id="ukl-link3"><div class="ukl-getlink" id="ukl-getlink3"></div></div><div class="ukl-link" id="ukl-link4"><div class="ukl-getlink" id="ukl-getlink4"></div></div></div><div class="ukl-utility-links"><div id="ukl-spring-search-label"><form action="https://libguides.uky.edu/srch.php" role="search"><label id="ukl-spring-search-label" for="searchTerm"><input type="text" id="ukl-search-term" name="q" placeholder="Search our Guides">&nbsp;</label><button type="submit" id="ukl-spring-btn">Search</button></form></div><div class="ukl-link" id="ukl-link5"><div id="ukl-getlink5"></div></div><div class="ukl-link" id="ukl-link6"><div id="ukl-getlink6"></div></div></div></div></div></div></div></header></div>',
```
Comment (nrsa222) [inline js/universalHeader.js]: It looks like `style="display:block;"` accidentally got added here and in `css/global_header_footer.css`.  I would remove it from here to avoid any inline styling.

Comment (libmanuk) [reply js/universalHeader.js]: I have added another commit to fix this.
